// Office intelligence — recovery audit events + the sink port (OFF-033).
//
// Every detected recovery candidate emits exactly ONE DomainEventEnvelope
// through the RecoveryEventSink port, mirroring the landed intelligence
// peers' EventSink shape byte-for-byte in structure (appendEvents(executor,
// events) inside the CALLER's transaction — see the margin engine's
// assessment-events, the memory engine's memory-events, and the exception
// engine's exception-events): the downstream consumers OFF-037 (the
// end-to-end construction reference scenario) and OFF-040 (analytics)
// consume recovery-candidate events like any other domain event.
//
// One documented local structural type (the dependency rule forbids
// importing the owning package):
// - RecoverySinkExecutor mirrors @office/persistence's SqlExecutor surface
//   (the `query` method) — a real implementation receives the caller's open
//   transaction executor exactly like the domain sinks do.
// - The envelope is built through @office/contracts' canonical parser, so
//   an emitted recovery event can never be invalid.
//
// Causality (A3): the recovery event is CAUSED BY the candidate's primary
// producing event — its causation id is that event's ledger id, and the
// correlation id of the source's causal chain is carried over. The
// envelope's source is 'system' (the candidate is machine-generated by the
// intelligence engine — never 'domain', never an adapter), the actor is
// the scan's requesting actor, and the entity refs point at the
// candidate's first referenced canonical record. The payload carries the
// JSON-safe recovery summary INCLUDING the proposed next actions' command
// references (suggestions only — the event carries data, never an
// execution).
import { CURRENT_SCHEMA_VERSION, parseDomainEventEnvelope } from '@office/contracts';
import type { DomainEventEnvelope, EntityRef } from '@office/contracts';
import { domainError, fail, ok } from '@office/domain-kernel';
import type { DomainError, DomainErrorContext, Result } from '@office/domain-kernel';
import { RECOVERY_DETECTED_EVENT } from './vocabulary';
import type { CandidateRecovery } from './candidates';
import { proposeNextActions } from './proposal';

// ---------------------------------------------------------------------------
// The sink executor port (local structural mirror of SqlExecutor).
// ---------------------------------------------------------------------------

/**
 * The executor surface a recovery sink needs (a local structural mirror of
 * @office/persistence's SqlExecutor — that package is not importable from
 * the intelligence layer; the shape is the port, mirroring the landed
 * intelligence peers' EventSink convention exactly).
 */
export interface RecoverySinkExecutor {
  readonly query: (
    text: string,
    values?: readonly unknown[],
  ) => Promise<{ rows: Record<string, unknown>[]; rowCount: number }>;
}

// ---------------------------------------------------------------------------
// The EventSink port (mirrors the landed intelligence peers' shape).
// ---------------------------------------------------------------------------

/**
 * THE recovery event sink port: append recovery events inside the caller's
 * transaction (the executor it hands over). A failure result MUST abort
 * the surrounding write, exactly like the domain packages' EventSink.
 */
export interface RecoveryEventSink {
  /**
   * Append `events` inside the transaction of `executor`. A failure result
   * MUST abort the surrounding mutation, so a partially-applied write can
   * never commit.
   */
  appendEvents(
    executor: RecoverySinkExecutor,
    events: readonly DomainEventEnvelope[],
  ): Promise<Result<true, DomainError>>;
}

/** One recorded append of the in-memory sink (test introspection). */
export interface RecordedRecoveryAppend {
  readonly executor: RecoverySinkExecutor;
  readonly events: readonly DomainEventEnvelope[];
}

/** The in-memory recovery event sink: records appends instead of writing (tests). */
export interface InMemoryRecoveryEventSink extends RecoveryEventSink {
  /** Every append call, in order (executor + events). */
  readonly appends: readonly RecordedRecoveryAppend[];
  /** Every recorded event, flattened across appends, in order. */
  readonly events: readonly DomainEventEnvelope[];
}

/** Create an in-memory recovery event sink for deterministic tests. */
export function createInMemoryRecoveryEventSink(): InMemoryRecoveryEventSink {
  const appends: RecordedRecoveryAppend[] = [];
  return {
    appends,
    get events(): readonly DomainEventEnvelope[] {
      return appends.flatMap((append) => append.events);
    },
    appendEvents: async (executor, events) => {
      appends.push({ executor, events: [...events] });
      return ok(true);
    },
  };
}

/** Build a typed sink failure (for tests and wiring guards). */
export const recoverySinkFailure = (
  reason: string,
  context?: DomainErrorContext,
): DomainError =>
  domainError(
    'invariant-violation',
    `recovery event sink rejected the append: ${reason}`,
    [{ code: 'recovery-sink-rejected', message: reason, path: null }],
    context,
  );

/** Convenience: a sink that always fails with a typed error (tests/limits). */
export const failingRecoveryEventSink = (reason: string): RecoveryEventSink => ({
  appendEvents: async () => fail(recoverySinkFailure(reason)),
});

// ---------------------------------------------------------------------------
// The recovery event envelope.
// ---------------------------------------------------------------------------

/** Grammar description of the recovery-candidate-detected event payload. */
export const RECOVERY_DETECTED_PAYLOAD_GRAMMAR =
  'recoveryCandidateDetected payload: { candidateId, candidateVersion, engine, scanId, detectedAt, kind, title, referencedRecords, severity, economicBasis, historicalBasis, evidenceRecordRefs, evidenceEventIds, evidenceAssessmentIds, evidenceOutcomeIds, evidenceBenchmarkIds, evidenceSetRefs, proposedNextActions } (JSON-safe summary of the CandidateRecovery + its proposed next actions)';

/** Build a typed failure for an unbuildable recovery event. */
const recoveryEventFailure = (reason: string): DomainError =>
  domainError(
    'invariant-violation',
    `the recovery candidate cannot be emitted as an event: ${reason}`,
    [{ code: 'recovery-event-valid', message: reason, path: null }],
  );

/**
 * Build the audit event of ONE detected recovery candidate: an
 * `intelligence.recoveryCandidateDetected` DomainEventEnvelope whose
 * causation id is the candidate's primary producing event's ledger id
 * (the detection is downstream of the change it assesses), whose
 * correlation id is carried over from the source's causal chain, whose
 * actor is the scan's requesting actor, and whose payload is the
 * JSON-safe recovery summary downstream consumers (OFF-037/040) read —
 * including the proposed next actions (SUGGESTIONS ONLY), the evidence
 * chain ids (A4 traceability survives the event boundary), and the
 * complete evidence-set reference tokens (the agents discipline).
 */
export function recoveryCandidateDetectedEnvelope(
  candidate: CandidateRecovery,
): Result<DomainEventEnvelope, DomainError> {
  const firstReferenced = candidate.referencedRecords[0];
  if (firstReferenced === undefined) {
    return fail(
      recoveryEventFailure('a recovery candidate must reference at least one canonical record'),
    );
  }
  const entityRef: EntityRef = {
    entityKind: firstReferenced.entityKind,
    entityId: firstReferenced.entityId,
  };
  const envelope = parseDomainEventEnvelope({
    kind: 'event',
    eventName: RECOVERY_DETECTED_EVENT,
    scope: candidate.scope,
    actor: candidate.actor,
    source: 'system',
    causality: {
      correlationId: candidate.primarySource.correlationId,
      causationId: candidate.primarySource.eventId,
    },
    schemaVersion: CURRENT_SCHEMA_VERSION,
    occurredAt: candidate.detectedAt,
    entityRefs: { before: null, after: entityRef },
    payload: {
      candidateId: candidate.candidateId,
      candidateVersion: candidate.candidateVersion,
      engine: candidate.engine,
      scanId: candidate.provenance.scanId,
      detectedAt: candidate.detectedAt,
      kind: candidate.kind,
      title: candidate.title,
      referencedRecords: candidate.referencedRecords.map((ref) => ({
        entityKind: ref.entityKind,
        entityId: ref.entityId,
      })),
      severity: {
        level: candidate.severity.level,
        reasons: [...candidate.severity.reasons],
      },
      economicBasis: {
        amountMinor: candidate.economicBasis.amountMinor,
        currency: candidate.economicBasis.currency,
        citedFrom: candidate.economicBasis.citedFrom,
        assessmentIds: [...candidate.economicBasis.assessmentIds],
      },
      historicalBasis: {
        outcomeIds: [...candidate.historicalBasis.outcomeIds],
        benchmarkIds: candidate.historicalBasis.benchmarks.map((fact) => fact.benchmarkId),
      },
      evidenceRecordRefs: candidate.evidence
        .filter((evidence) => evidence.kind === 'record')
        .map((evidence) => (evidence.kind === 'record' ? evidence.ref.entityId : null)),
      evidenceEventIds: candidate.evidence
        .filter((evidence) => evidence.kind === 'event')
        .map((evidence) => (evidence.kind === 'event' ? evidence.eventId : null)),
      evidenceAssessmentIds: candidate.evidence
        .filter((evidence) => evidence.kind === 'assessment')
        .map((evidence) => (evidence.kind === 'assessment' ? evidence.assessmentId : null)),
      evidenceOutcomeIds: candidate.evidence
        .filter((evidence) => evidence.kind === 'outcome')
        .map((evidence) => (evidence.kind === 'outcome' ? evidence.outcomeId : null)),
      evidenceBenchmarkIds: candidate.evidence
        .filter((evidence) => evidence.kind === 'benchmark')
        .map((evidence) => (evidence.kind === 'benchmark' ? evidence.benchmarkId : null)),
      evidenceSetRefs: candidate.evidenceSet.items.map((item) => item.ref),
      proposedNextActions: proposeNextActions(candidate).map((action) => ({
        commandName: action.command.commandName,
        title: action.title,
        confidence: {
          level: action.confidence.level,
          reasons: [...action.confidence.reasons],
        },
        payload: action.command.payload,
      })),
    },
  });
  if (!envelope.ok) {
    return fail(
      recoveryEventFailure(
        `the recoveryCandidateDetected envelope failed its own contract: ${JSON.stringify(envelope.error)}`,
      ),
    );
  }
  return ok(envelope.value);
}

/**
 * Emit ONE detected recovery candidate through a RecoveryEventSink — the
 * convenience the runtime wires: build the envelope and hand it to the
 * sink with the caller's executor. The sink's failure propagates (typed) so
 * the caller's transaction aborts.
 */
export async function emitRecoveryCandidateDetected(
  sink: RecoveryEventSink,
  executor: RecoverySinkExecutor,
  candidate: CandidateRecovery,
): Promise<Result<true, DomainError>> {
  const envelope = recoveryCandidateDetectedEnvelope(candidate);
  if (!envelope.ok) return envelope;
  return sink.appendEvents(executor, [envelope.value]);
}
