// Office intelligence — exception events + the sink port (OFF-019).
//
// Every detected exception emits exactly ONE DomainEventEnvelope through
// the ExceptionEventSink port, mirroring the landed intelligence peers'
// EventSink shape byte-for-byte in structure (appendEvents(executor,
// events) inside the CALLER's transaction — see the margin engine's
// assessment-events and the memory engine's memory-events): the downstream
// consumers OFF-030 (views), OFF-033 (agent runtime), and OFF-035 (chips)
// consume exception events like any other domain event.
//
// Two documented local structural types (the dependency rule forbids
// importing the owning packages):
// - ExceptionSinkExecutor mirrors @office/persistence's SqlExecutor
//   surface (the `query` method) — a real implementation receives the
//   caller's open transaction executor exactly like the domain sinks do.
// - The envelope is built through @office/contracts' canonical parser, so
//   an emitted exception event can never be invalid.
//
// Causality (A3): the exception event is CAUSED BY the exception's primary
// producing event — its causation id is that event's ledger id (the events
// package's causedByEvent convention), and the correlation id of the
// source's causal chain is carried over. The envelope's source is 'system'
// (the exception is machine-generated by the intelligence engine — never
// 'domain', never an adapter), the actor is the scan's requesting actor,
// and the entity refs point at the exception's primary affected entity.
// The payload carries the JSON-safe control-tower summary INCLUDING the
// suggested next actions' command references (suggestions only — the event
// carries data, never an execution).
import { CURRENT_SCHEMA_VERSION, parseDomainEventEnvelope } from '@office/contracts';
import type { DomainEventEnvelope, EntityRef } from '@office/contracts';
import { domainError, fail, ok } from '@office/domain-kernel';
import type { DomainError, DomainErrorContext, Result } from '@office/domain-kernel';
import { EXCEPTION_DETECTED_EVENT } from './vocabulary';
import type { Exception } from './model';
import { suggestNextActions } from './next-actions';

// ---------------------------------------------------------------------------
// The sink executor port (local structural mirror of SqlExecutor).
// ---------------------------------------------------------------------------

/**
 * The executor surface an exception sink needs (a local structural mirror
 * of @office/persistence's SqlExecutor — that package is not importable
 * from the intelligence layer; the shape is the port, mirroring the landed
 * domain EventSink convention exactly).
 */
export interface ExceptionSinkExecutor {
  readonly query: (
    text: string,
    values?: readonly unknown[],
  ) => Promise<{ rows: Record<string, unknown>[]; rowCount: number }>;
}

// ---------------------------------------------------------------------------
// The EventSink port (mirrors the landed intelligence peers' shape).
// ---------------------------------------------------------------------------

/**
 * THE exception event sink port: append exception events inside the
 * caller's transaction (the executor it hands over). A failure result MUST
 * abort the surrounding write, exactly like the domain packages' EventSink.
 */
export interface ExceptionEventSink {
  /**
   * Append `events` inside the transaction of `executor`. A failure result
   * MUST abort the surrounding mutation, so a partially-applied write can
   * never commit.
   */
  appendEvents(
    executor: ExceptionSinkExecutor,
    events: readonly DomainEventEnvelope[],
  ): Promise<Result<true, DomainError>>;
}

/** One recorded append of the in-memory sink (test introspection). */
export interface RecordedExceptionAppend {
  readonly executor: ExceptionSinkExecutor;
  readonly events: readonly DomainEventEnvelope[];
}

/** The in-memory exception event sink: records appends instead of writing (tests). */
export interface InMemoryExceptionEventSink extends ExceptionEventSink {
  /** Every append call, in order (executor + events). */
  readonly appends: readonly RecordedExceptionAppend[];
  /** Every recorded event, flattened across appends, in order. */
  readonly events: readonly DomainEventEnvelope[];
}

/** Create an in-memory exception event sink for deterministic tests. */
export function createInMemoryExceptionEventSink(): InMemoryExceptionEventSink {
  const appends: RecordedExceptionAppend[] = [];
  return {
    appends,
    get events(): readonly DomainEventEnvelope[] {
      return appends.flatMap((append) => append.events);
    },
    appendEvents: async (executor, events) => {
      appends.push({ executor, events: [...events] });
      return ok(true);
    },
  };
}

/** Build a typed sink failure (for tests and wiring guards). */
export const exceptionSinkFailure = (
  reason: string,
  context?: DomainErrorContext,
): DomainError =>
  domainError(
    'invariant-violation',
    `exception event sink rejected the append: ${reason}`,
    [{ code: 'exception-sink-rejected', message: reason, path: null }],
    context,
  );

/** Convenience: a sink that always fails with a typed error (tests/limits). */
export const failingExceptionEventSink = (reason: string): ExceptionEventSink => ({
  appendEvents: async () => fail(exceptionSinkFailure(reason)),
});

// ---------------------------------------------------------------------------
// The exception event envelope.
// ---------------------------------------------------------------------------

/** Grammar description of the exception-detected event payload. */
export const EXCEPTION_DETECTED_PAYLOAD_GRAMMAR =
  'exceptionDetected payload: { exceptionId, exceptionVersion, engine, scanId, detectedAt, kind, title, affected, severity, economicImpact, evidenceEventIds, evidenceAssessmentIds, evidenceBenchmarkIds, nextActions } (JSON-safe summary of the Exception + its suggested next actions)';

/** Build a typed failure for an unbuildable exception event. */
const exceptionEventFailure = (reason: string): DomainError =>
  domainError(
    'invariant-violation',
    `the exception cannot be emitted as an event: ${reason}`,
    [{ code: 'exception-event-valid', message: reason, path: null }],
  );

/**
 * Build the audit event of ONE detected exception: an
 * `intelligence.exceptionDetected` DomainEventEnvelope whose causation id
 * is the exception's primary producing event's ledger id (the
 * causedByEvent convention — the detection is downstream of the change it
 * assesses), whose correlation id is carried over from the source's causal
 * chain, whose actor is the scan's requesting actor, and whose payload is
 * the JSON-safe control-tower summary downstream consumers (OFF-030/033/
 * 035) read — including the suggested next actions (SUGGESTIONS ONLY) and
 * every evidence id (A4 traceability survives the event boundary).
 */
export function exceptionDetectedEnvelope(
  exception: Exception,
): Result<DomainEventEnvelope, DomainError> {
  const firstAffected = exception.affected[0];
  if (firstAffected === undefined) {
    return fail(
      exceptionEventFailure('an exception must carry at least one affected entity ref'),
    );
  }
  const entityRef: EntityRef = {
    entityKind: firstAffected.entityKind,
    entityId: firstAffected.entityId,
  };
  const envelope = parseDomainEventEnvelope({
    kind: 'event',
    eventName: EXCEPTION_DETECTED_EVENT,
    scope: exception.scope,
    actor: exception.actor,
    source: 'system',
    causality: {
      correlationId: exception.primarySource.correlationId,
      causationId: exception.primarySource.eventId,
    },
    schemaVersion: CURRENT_SCHEMA_VERSION,
    occurredAt: exception.detectedAt,
    entityRefs: { before: null, after: entityRef },
    payload: {
      exceptionId: exception.exceptionId,
      exceptionVersion: exception.exceptionVersion,
      engine: exception.engine,
      scanId: exception.provenance.scanId,
      detectedAt: exception.detectedAt,
      kind: exception.kind,
      title: exception.title,
      affected: exception.affected.map((ref) => ({
        entityKind: ref.entityKind,
        entityId: ref.entityId,
      })),
      severity: {
        level: exception.severity.level,
        reasons: [...exception.severity.reasons],
      },
      economicImpact: {
        amountMinor: exception.economicImpact.amountMinor,
        currency: exception.economicImpact.currency,
        assessmentIds: [...exception.economicImpact.assessmentIds],
      },
      evidenceEventIds: exception.evidence
        .filter((evidence) => evidence.kind === 'event')
        .map((evidence) => evidence.eventId),
      evidenceAssessmentIds: exception.evidence
        .filter((evidence) => evidence.kind === 'assessment')
        .map((evidence) => evidence.assessmentId),
      evidenceBenchmarkIds: exception.evidence
        .filter((evidence) => evidence.kind === 'benchmark')
        .map((evidence) => evidence.benchmarkId),
      nextActions: suggestNextActions(exception).map((action) => ({
        commandName: action.command.commandName,
        title: action.title,
        confidence: {
          level: action.confidence.level,
          reasons: [...action.confidence.reasons],
        },
        payload: action.command.payload,
      })),
    },
  });
  if (!envelope.ok) {
    return fail(
      exceptionEventFailure(
        `the exceptionDetected envelope failed its own contract: ${JSON.stringify(envelope.error)}`,
      ),
    );
  }
  return ok(envelope.value);
}

/**
 * Emit ONE detected exception through an ExceptionEventSink — the
 * convenience the runtime wires: build the envelope and hand it to the sink
 * with the caller's executor. The sink's failure propagates (typed) so the
 * caller's transaction aborts.
 */
export async function emitExceptionDetected(
  sink: ExceptionEventSink,
  executor: ExceptionSinkExecutor,
  exception: Exception,
): Promise<Result<true, DomainError>> {
  const envelope = exceptionDetectedEnvelope(exception);
  if (!envelope.ok) return envelope;
  return sink.appendEvents(executor, [envelope.value]);
}
