// Office intelligence — stack analysis audit events + the sink port (OFF-035).
//
// Every assessed subject (each observed external system, each installed
// app) emits exactly ONE DomainEventEnvelope through the StackEventSink
// port, mirroring the landed intelligence peers' EventSink shape
// byte-for-byte in structure (appendEvents(executor, events) inside the
// CALLER's transaction — see the margin engine's assessment-events, the
// memory engine's memory-events, the exception engine's exception-events,
// and the revenue engine's recovery events): the downstream consumers
// OFF-038 (release gates) and OFF-040 (analytics) consume
// replacement-assessed events like any other domain event.
//
// One documented local structural type (the dependency rule forbids
// importing the owning package):
// - StackSinkExecutor mirrors @office/persistence's SqlExecutor surface
//   (the `query` method) — a real implementation receives the caller's open
//   transaction executor exactly like the domain sinks do.
// - The envelope is built through @office/contracts' canonical parser, so
//   an emitted stack analysis event can never be invalid.
//
// Causality (A3): the stack analysis events take CALLER-SUPPLIED causality
// (correlation + causation ids — the same convention as the memory engine's
// benchmark/lesson envelopes): the scan is a derived projection over
// already-recorded marketplace/memory records, so the caller names the
// causal chain it belongs to. The envelope's source is 'system' (the
// assessment is machine-generated by the intelligence engine — never
// 'domain', never an adapter), the actor is the scan's requesting actor,
// and the entity refs point at the assessed subject when it is canonical
// (an installed app's installation identity; an external system is not a
// canonical entity, so its events carry both refs null — the envelope's
// documented not-bound-to-a-single-entity form). The payload carries the
// JSON-safe assessment summary INCLUDING the exposed score composition and
// the suggestion — data only, never an execution, never a command.
import { CURRENT_SCHEMA_VERSION, parseDomainEventEnvelope } from '@office/contracts';
import type {
  CausationId,
  CorrelationId,
  DomainEventEnvelope,
  EntityRef,
} from '@office/contracts';
import { domainError, fail, ok } from '@office/domain-kernel';
import type { DomainError, DomainErrorContext, Result } from '@office/domain-kernel';
import { APP_INSTALLATION_KIND, STACK_ASSESSED_EVENT } from './vocabulary';
import type { ReplacementAssessment } from './replacement';

// ---------------------------------------------------------------------------
// The sink executor port (local structural mirror of SqlExecutor).
// ---------------------------------------------------------------------------

/**
 * The executor surface a stack sink needs (a local structural mirror of
 * @office/persistence's SqlExecutor — that package is not importable from
 * the intelligence layer; the shape is the port, mirroring the landed
 * intelligence peers' EventSink convention exactly).
 */
export interface StackSinkExecutor {
  readonly query: (
    text: string,
    values?: readonly unknown[],
  ) => Promise<{ rows: Record<string, unknown>[]; rowCount: number }>;
}

// ---------------------------------------------------------------------------
// The EventSink port (mirrors the landed intelligence peers' shape).
// ---------------------------------------------------------------------------

/**
 * THE stack analysis event sink port: append stack analysis events inside
 * the caller's transaction (the executor it hands over). A failure result
 * MUST abort the surrounding write, exactly like the domain packages'
 * EventSink.
 */
export interface StackEventSink {
  /**
   * Append `events` inside the transaction of `executor`. A failure result
   * MUST abort the surrounding mutation, so a partially-applied write can
   * never commit.
   */
  appendEvents(
    executor: StackSinkExecutor,
    events: readonly DomainEventEnvelope[],
  ): Promise<Result<true, DomainError>>;
}

/** One recorded append of the in-memory sink (test introspection). */
export interface RecordedStackAppend {
  readonly executor: StackSinkExecutor;
  readonly events: readonly DomainEventEnvelope[];
}

/** The in-memory stack event sink: records appends instead of writing (tests). */
export interface InMemoryStackEventSink extends StackEventSink {
  /** Every append call, in order (executor + events). */
  readonly appends: readonly RecordedStackAppend[];
  /** Every recorded event, flattened across appends, in order. */
  readonly events: readonly DomainEventEnvelope[];
}

/** Create an in-memory stack event sink for deterministic tests. */
export function createInMemoryStackEventSink(): InMemoryStackEventSink {
  const appends: RecordedStackAppend[] = [];
  return {
    appends,
    get events(): readonly DomainEventEnvelope[] {
      return appends.flatMap((append) => append.events);
    },
    appendEvents: async (executor, events) => {
      appends.push({ executor, events: [...events] });
      return ok(true);
    },
  };
}

/** Build a typed sink failure (for tests and wiring guards). */
export const stackSinkFailure = (
  reason: string,
  context?: DomainErrorContext,
): DomainError =>
  domainError(
    'invariant-violation',
    `stack analysis event sink rejected the append: ${reason}`,
    [{ code: 'stack-sink-rejected', message: reason, path: null }],
    context,
  );

/** Convenience: a sink that always fails with a typed error (tests/limits). */
export const failingStackEventSink = (reason: string): StackEventSink => ({
  appendEvents: async () => fail(stackSinkFailure(reason)),
});

// ---------------------------------------------------------------------------
// The replacement-assessed event envelope.
// ---------------------------------------------------------------------------

/** Grammar description of the replacement-assessed event payload. */
export const STACK_ASSESSED_PAYLOAD_GRAMMAR =
  'replacementAssessed payload: { assessmentId, assessmentVersion, engine, scanId, assessedAt, kind, title, subject, score, coveredCapabilities, uncoveredCapabilities, suggestion, evidenceSystemRefs, evidenceLinkIds, evidenceReleaseIds, evidenceEntitlementIds, evidenceOutcomeIds, evidenceBenchmarkIds, performanceBasis, commandSurface?, subscriptionSurface? } (JSON-safe summary of the ReplacementAssessment)';

/** The caller-supplied causality of one emitted assessment event (A3). */
export interface StackCausality {
  /** The correlation id of the causal chain this emission belongs to. */
  readonly correlationId: CorrelationId;
  /** The causation id naming the causing activity (the caller's chain). */
  readonly causationId: CausationId;
}

/** Build a typed failure for an unbuildable stack analysis event. */
const stackEventFailure = (reason: string): DomainError =>
  domainError(
    'invariant-violation',
    `the stack replacement assessment cannot be emitted as an event: ${reason}`,
    [{ code: 'stack-event-valid', message: reason, path: null }],
  );

/**
 * Build the audit event of ONE replacement assessment: an
 * `intelligence.replacementAssessed` DomainEventEnvelope with
 * caller-supplied causality, sourced 'system', acted by the scan's
 * requesting actor, scoped to the scan's execution scope, whose payload is
 * the JSON-safe assessment summary downstream consumers (OFF-038/040)
 * read — including the EXPOSED score composition (the recomputable
 * formula + counts + exact rational value), the covered/uncovered
 * capability lists, the typed suggestion, and every evidence id (A4
 * traceability survives the event boundary).
 */
export function replacementAssessedEnvelope(
  assessment: ReplacementAssessment,
  causality: StackCausality,
): Result<DomainEventEnvelope, DomainError> {
  const entityRef: EntityRef | null =
    assessment.coverage.kind === 'installed-app-coverage'
      ? {
          entityKind: APP_INSTALLATION_KIND,
          entityId: assessment.coverage.installationId,
        }
      : null;

  const coveredCapabilities = coverageCoveredCapabilities(assessment);
  const uncoveredCapabilities = coverageUncoveredCapabilities(assessment);

  const payload: Record<string, unknown> = {
    assessmentId: assessment.assessmentId,
    assessmentVersion: assessment.assessmentVersion,
    engine: assessment.engine,
    scanId: assessment.provenance.scanId,
    assessedAt: assessment.assessedAt,
    kind: assessment.kind,
    title: assessment.title,
    subject: subjectSummaryOf(assessment),
    score: {
      formula: assessment.score.formula,
      value:
        assessment.score.value === null
          ? null
          : {
              numerator: assessment.score.value.numerator,
              denominator: assessment.score.value.denominator,
            },
      coveredCount: assessment.score.coveredCount,
      surfaceCount: assessment.score.surfaceCount,
    },
    coveredCapabilities,
    uncoveredCapabilities,
    suggestion: {
      kind: assessment.suggestion.kind,
      rationale: assessment.suggestion.rationale,
      reasons: [...assessment.suggestion.reasons],
    },
    evidenceSystemRefs: assessment.evidence
      .filter((evidence) => evidence.evidenceKind === 'system')
      .map((evidence) =>
        evidence.evidenceKind === 'system'
          ? { adapterKind: evidence.adapterKind, systemId: evidence.systemId }
          : null,
      ),
    evidenceLinkIds: assessment.evidence
      .filter((evidence) => evidence.evidenceKind === 'installation-link')
      .map((evidence) => (evidence.evidenceKind === 'installation-link' ? evidence.linkId : null)),
    evidenceReleaseIds: assessment.evidence
      .filter((evidence) => evidence.evidenceKind === 'release')
      .map((evidence) => (evidence.evidenceKind === 'release' ? evidence.releaseId : null)),
    evidenceEntitlementIds: assessment.evidence
      .filter((evidence) => evidence.evidenceKind === 'entitlement')
      .map((evidence) =>
        evidence.evidenceKind === 'entitlement' ? evidence.entitlementId : null,
      ),
    evidenceOutcomeIds: assessment.evidence
      .filter((evidence) => evidence.evidenceKind === 'outcome')
      .map((evidence) => (evidence.evidenceKind === 'outcome' ? evidence.outcomeId : null)),
    evidenceBenchmarkIds: assessment.evidence
      .filter((evidence) => evidence.evidenceKind === 'benchmark')
      .map((evidence) => (evidence.evidenceKind === 'benchmark' ? evidence.benchmarkId : null)),
    performanceBasis:
      assessment.performanceBasis === null
        ? null
        : {
            outcomeIds: [...assessment.performanceBasis.outcomeIds],
            benchmarkIds: [...assessment.performanceBasis.benchmarkIds],
          },
  };
  if (assessment.coverage.kind === 'installed-app-coverage') {
    payload['commandSurface'] = [...assessment.coverage.commandSurface];
    payload['subscriptionSurface'] = [...assessment.coverage.subscriptionSurface];
  }

  const envelope = parseDomainEventEnvelope({
    kind: 'event',
    eventName: STACK_ASSESSED_EVENT,
    scope: assessment.scope,
    actor: assessment.actor,
    source: 'system',
    causality: {
      correlationId: causality.correlationId,
      causationId: causality.causationId,
    },
    schemaVersion: CURRENT_SCHEMA_VERSION,
    occurredAt: assessment.assessedAt,
    entityRefs: { before: null, after: entityRef },
    payload,
  });
  if (!envelope.ok) {
    return fail(
      stackEventFailure(
        `the replacementAssessed envelope failed its own contract: ${JSON.stringify(envelope.error)}`,
      ),
    );
  }
  return ok(envelope.value);
}

/**
 * Emit ONE replacement assessment through a StackEventSink — the
 * convenience the runtime wires: build the envelope and hand it to the
 * sink with the caller's executor. The sink's failure propagates (typed)
 * so the caller's transaction aborts.
 */
export async function emitReplacementAssessed(
  sink: StackEventSink,
  executor: StackSinkExecutor,
  assessment: ReplacementAssessment,
  causality: StackCausality,
): Promise<Result<true, DomainError>> {
  const envelope = replacementAssessedEnvelope(assessment, causality);
  if (!envelope.ok) return envelope;
  return sink.appendEvents(executor, [envelope.value]);
}

// ---------------------------------------------------------------------------
// Payload helpers (the covered/uncovered split in both directions).
// ---------------------------------------------------------------------------

const coverageCoveredCapabilities = (assessment: ReplacementAssessment): string[] => {
  if (assessment.coverage.kind === 'external-system-coverage') {
    return assessment.coverage.covered.map((entry) => entry.capability);
  }
  return assessment.coverage.overlapping.map((entry) => entry.capability);
};

const coverageUncoveredCapabilities = (assessment: ReplacementAssessment): string[] => {
  if (assessment.coverage.kind === 'external-system-coverage') {
    return assessment.coverage.gaps.map((entry) => entry.capability);
  }
  return assessment.coverage.unique.map((entry) => entry.capability);
};

const subjectSummaryOf = (assessment: ReplacementAssessment): Record<string, unknown> => {
  if (assessment.coverage.kind === 'external-system-coverage') {
    return {
      adapterKind: assessment.coverage.adapterKind,
      systemId: assessment.coverage.systemId,
      tenantId: assessment.coverage.tenantId,
    };
  }
  return {
    appId: assessment.coverage.appId,
    installationId: assessment.coverage.installationId,
    linkId: assessment.coverage.linkId,
    releaseId: assessment.coverage.releaseId,
    entitlementId: assessment.coverage.entitlementId,
    currentVersion: assessment.coverage.currentVersion,
    tenantId: assessment.coverage.tenantId,
  };
};
