// Office intelligence — assessment events + the sink port (OFF-014).
//
// Every assessment emits exactly ONE DomainEventEnvelope through the
// AssessmentEventSink port, mirroring the landed domain packages' EventSink
// shape byte-for-byte in structure (appendEvents(executor, events) inside
// the CALLER's transaction — see packages/domain/*/src/events.ts): the
// downstream consumers OFF-015 (enterprise memory) and OFF-018
// (recommendations) consume assessment events like any other domain event.
//
// Two documented local structural types (the dependency rule forbids
// importing the owning packages):
// - AssessmentSinkExecutor mirrors @office/persistence's SqlExecutor
//   surface (the `query` method) — a real implementation receives the
//   caller's open transaction executor exactly like the domain sinks do.
// - The envelope is built through @office/contracts' canonical parser, so
//   an emitted assessment event can never be invalid.
//
// Causality (A3): the assessment event is CAUSED BY the source change
// event — its causation id is the source event's ledger id (the events
// package's causedByEvent convention), and the correlation id of the
// source event's causal chain is carried over. The envelope's source is
// 'system' (the assessment is machine-generated by the intelligence
// engine — never 'domain', never an adapter), the actor is the requesting
// context's actor (who triggered the assessment), and the entity refs
// point at the assessed change event.
import { CURRENT_SCHEMA_VERSION, parseDomainEventEnvelope } from '@office/contracts';
import type { DomainEventEnvelope, EntityRef } from '@office/contracts';
import { domainError, fail, ok } from '@office/domain-kernel';
import type { DomainError, DomainErrorContext, Result } from '@office/domain-kernel';
import { MARGIN_ASSESSED_EVENT } from './vocabulary';
import { CHANGE_EVENT_KIND } from './model';
import type { ImpactAssessment } from './model';

// ---------------------------------------------------------------------------
// The sink executor port (local structural mirror of SqlExecutor).
// ---------------------------------------------------------------------------

/**
 * The executor surface an assessment sink needs (a local structural mirror
 * of @office/persistence's SqlExecutor — that package is not importable
 * from the intelligence layer; the shape is the port, mirroring the landed
 * domain EventSink convention exactly).
 */
export interface AssessmentSinkExecutor {
  readonly query: (
    text: string,
    values?: readonly unknown[],
  ) => Promise<{ rows: Record<string, unknown>[]; rowCount: number }>;
}

// ---------------------------------------------------------------------------
// The EventSink port (mirrors the landed domain packages' shape).
// ---------------------------------------------------------------------------

/**
 * THE assessment event sink port: append assessment events inside the
 * caller's transaction (the executor it hands over). A failure result MUST
 * abort the surrounding write, exactly like the domain packages' EventSink.
 */
export interface AssessmentEventSink {
  /**
   * Append `events` inside the transaction of `executor`. A failure result
   * MUST abort the surrounding mutation, so a partially-applied write can
   * never commit.
   */
  appendEvents(
    executor: AssessmentSinkExecutor,
    events: readonly DomainEventEnvelope[],
  ): Promise<Result<true, DomainError>>;
}

/** One recorded append of the in-memory sink (test introspection). */
export interface RecordedAssessmentAppend {
  readonly executor: AssessmentSinkExecutor;
  readonly events: readonly DomainEventEnvelope[];
}

/** The in-memory assessment event sink: records appends instead of writing (tests). */
export interface InMemoryAssessmentEventSink extends AssessmentEventSink {
  /** Every append call, in order (executor + events). */
  readonly appends: readonly RecordedAssessmentAppend[];
  /** Every recorded event, flattened across appends, in order. */
  readonly events: readonly DomainEventEnvelope[];
}

/** Create an in-memory assessment event sink for deterministic tests. */
export function createInMemoryAssessmentEventSink(): InMemoryAssessmentEventSink {
  const appends: RecordedAssessmentAppend[] = [];
  return {
    appends,
    get events(): readonly DomainEventEnvelope[] {
      return appends.flatMap((append) => append.events);
    },
    appendEvents: async (executor, events) => {
      appends.push({ executor, events: [...events] });
      return ok(true);
    },
  };
}

/** Build a typed sink failure (for tests and wiring guards). */
export const assessmentSinkFailure = (
  reason: string,
  context?: DomainErrorContext,
): DomainError =>
  domainError(
    'invariant-violation',
    `assessment event sink rejected the append: ${reason}`,
    [{ code: 'assessment-sink-rejected', message: reason, path: null }],
    context,
  );

/** Convenience: a sink that always fails with a typed error (tests/limits). */
export const failingAssessmentEventSink = (reason: string): AssessmentEventSink => ({
  appendEvents: async () => fail(assessmentSinkFailure(reason)),
});

// ---------------------------------------------------------------------------
// The assessment event envelope.
// ---------------------------------------------------------------------------

/** Grammar description of the margin-assessed event payload. */
export const MARGIN_ASSESSED_PAYLOAD_GRAMMAR =
  'marginAssessed payload: { assessmentId, assessmentVersion, engine, sourceEventId, changeEventId, contractId, confidence, costImpact, scheduleImpact, entitlement, margin, evidenceEventIds } (JSON-safe summary of the ImpactAssessment)';

/** Build a typed failure for an unbuildable assessment event. */
const assessmentEventFailure = (reason: string): DomainError =>
  domainError(
    'invariant-violation',
    `the assessment cannot be emitted as an event: ${reason}`,
    [{ code: 'assessment-event-valid', message: reason, path: null }],
  );

/**
 * Build the audit event of ONE assessment: an `intelligence.marginAssessed`
 * DomainEventEnvelope whose causation id is the source change event's
 * ledger id (the causedByEvent convention — the assessment is downstream
 * of the change it assesses), whose correlation id is carried over from
 * the source event's causal chain, whose actor is the requesting context's
 * actor, and whose payload is the JSON-safe summary downstream consumers
 * (OFF-015/OFF-018) read. Every number in the payload carries its source
 * event ids (A4 traceability survives the event boundary).
 */
export function marginAssessmentEnvelope(
  assessment: ImpactAssessment,
): Result<DomainEventEnvelope, DomainError> {
  const changeEventRef: EntityRef = {
    entityKind: CHANGE_EVENT_KIND,
    entityId: assessment.source.changeEventId,
  };
  const envelope = parseDomainEventEnvelope({
    kind: 'event',
    eventName: MARGIN_ASSESSED_EVENT,
    scope: assessment.scope,
    actor: assessment.actor,
    source: 'system',
    causality: {
      correlationId: assessment.source.correlationId,
      causationId: assessment.source.eventId,
    },
    schemaVersion: CURRENT_SCHEMA_VERSION,
    occurredAt: assessment.assessedAt,
    entityRefs: { before: null, after: changeEventRef },
    payload: {
      assessmentId: assessment.assessmentId,
      assessmentVersion: assessment.assessmentVersion,
      engine: assessment.engine,
      sourceEventId: assessment.query.sourceEventId,
      changeEventId: assessment.source.changeEventId,
      contractId: assessment.source.contractId,
      confidence: {
        level: assessment.confidence.level,
        reasons: [...assessment.confidence.reasons],
      },
      costImpact: {
        budgetRevisionDeltaMinor: assessment.costImpact.budgetRevisionDeltaMinor,
        currency: assessment.marginPosition.currency,
        itemDeltas: assessment.costImpact.itemDeltas.map((delta) => ({
          budgetId: delta.budgetId,
          costItemId: delta.costItemId,
          amountMinor: delta.amountMinor,
          sourceEventId: delta.source.eventId,
        })),
        revisionAnchors: assessment.costImpact.revisionAnchors.map((anchor) => ({
          budgetId: anchor.budgetId,
          revisionId: anchor.revisionId,
          sourceEventId: anchor.source.eventId,
        })),
      },
      scheduleImpact: {
        projectDurationDelta: assessment.scheduleImpact.projectDurationDelta,
        preProjectDuration: assessment.scheduleImpact.preProjectDuration,
        currentProjectDuration: assessment.scheduleImpact.currentProjectDuration,
        activityDeltas: assessment.scheduleImpact.activityDeltas.map((delta) => ({
          activityId: delta.activityId,
          code: delta.code,
          earlyStartDelta: delta.earlyStartDelta,
          earlyFinishDelta: delta.earlyFinishDelta,
          sourceEventIds: delta.drivers.map((driver) => driver.eventId),
        })),
      },
      entitlement: {
        status: assessment.entitlementImpact.status,
        approvedValueMinor: assessment.entitlementImpact.approvedValueMinor,
        rejectedValueMinor: assessment.entitlementImpact.rejectedValueMinor,
        pendingValueMinor: assessment.entitlementImpact.pendingValueMinor,
        currency: assessment.marginPosition.currency,
        orders: assessment.entitlementImpact.orders.map((order) => ({
          changeOrderId: order.changeOrderId,
          valueMinor: order.valueMinor,
          status: order.status,
          submissionEventId: order.submissionSource.eventId,
          decisionEventId: order.decisionSource === null ? null : order.decisionSource.eventId,
          claims: order.claims.map((claim) => ({
            claimReferenceId: claim.claimReferenceId,
            claimEntityKind: claim.claimEntityKind,
            claimEntityId: claim.claimEntityId,
            sourceEventId: claim.source.eventId,
          })),
        })),
      },
      margin: {
        currency: assessment.marginPosition.currency,
        contractedValueMinor: assessment.marginPosition.contractedValue.amountMinor,
        committedCostMinor: assessment.marginPosition.committedCost.amountMinor,
        budgetedCostMinor: assessment.marginPosition.budgetedCost.amountMinor,
        projectedCostMinor: assessment.marginPosition.projectedCost.amountMinor,
        marginMinor: assessment.marginPosition.marginMinor,
        marginOverCommittedMinor: assessment.marginPosition.marginOverCommittedMinor,
        layerEvidenceEventIds: {
          contractedValue: assessment.marginPosition.contractedValue.evidence.map(
            (reference) => reference.eventId,
          ),
          committedCost: assessment.marginPosition.committedCost.evidence.map(
            (reference) => reference.eventId,
          ),
          budgetedCost: assessment.marginPosition.budgetedCost.evidence.map(
            (reference) => reference.eventId,
          ),
          projectedCost: assessment.marginPosition.projectedCost.evidence.map(
            (reference) => reference.eventId,
          ),
        },
      },
      policyContext: {
        capabilities: [...assessment.policyContext.capabilities],
        requiredCapabilities: [...assessment.policyContext.requiredCapabilities],
        policyRuleCount: assessment.policyContext.policyRuleCount,
        decision: assessment.policyContext.decision,
      },
      evidenceEventIds: assessment.evidence.map((reference) => reference.eventId),
    },
  });
  if (!envelope.ok) {
    return fail(
      assessmentEventFailure(
        `the marginAssessed envelope failed its own contract: ${JSON.stringify(envelope.error)}`,
      ),
    );
  }
  return ok(envelope.value);
}

/**
 * Emit ONE assessment through an AssessmentEventSink — the convenience the
 * runtime wires: build the envelope and hand it to the sink with the
 * caller's executor. The sink's failure propagates (typed) so the caller's
 * transaction aborts.
 */
export async function emitMarginAssessment(
  sink: AssessmentEventSink,
  executor: AssessmentSinkExecutor,
  assessment: ImpactAssessment,
): Promise<Result<true, DomainError>> {
  const envelope = marginAssessmentEnvelope(assessment);
  if (!envelope.ok) return envelope;
  return sink.appendEvents(executor, [envelope.value]);
}
